### ISSUE TITLE
Add composer support

### ISSUE THREAD

**Issue by DavidePastore** [weberhofer/jsonrpcphp#2]
[It would be nice](https://getcomposer.org/). :cake:

**Comment by weberhofer** [comment]
Please try it out; I currenlty don't have enough time to test.

**Comment by DavidePastore** [comment]
I'm trying to use it.
**composer.json**:

    {
        "name": "davidepastore/jsonrpctest",
        "require": {
            "weberhofer/jsonrpcphp": "2.1-beta1"
        }
    }

**index.php**

    <?php
    require 'vendor/autoload.php';
    $myJSONRPCClient = new \org\jsonrpcphp\JsonRPCClient('http://www.example.com/' );

**Error**:

**Fatal error**: Class 'org\jsonrpcphp\JsonRPCClient' not found in **C:\xampp\htdocs\jsonrpc\index.php** on line 3

**Comment by weberhofer** [comment]
I have created a beta2 which fixes this issue. Please test.

**Comment by DavidePastore** [comment]
Using the same code above (changing the version of jsonrpcphp), it works fine. Good job @weberhofer  :palm_tree:

**Comment by weberhofer** [comment]
fixed with release 2.1.0

**Comment by brammeleman** [comment]
This issue still exists in 2.1.0. Getting:
```PHP Fatal error:  Class 'org\\jsonrpcphp\\jsonRPCClient' not found in .....```

Tested with: ```PHP 5.5.9-1ubuntu4.7``` and ```PHP 5.3.10-1ubuntu3.17```

**Comment by weberhofer** [comment]
Can you please test with the latest dev-version? I have made the sources PSR2 compatible and fixed a issue which caused the namespace not to be recognized correctly with some versions of PHP.

**Comment by brammeleman** [comment]
Mmmm sorry for bothering you.. I've been staring over that little lowercase 'j'....
Cheers,

Bram

**Comment by Jan-E** [comment]
@brammeleman Curious: did you happen to copy/paste something from https://manual.limesurvey.org/RemoteControl_2_API#PHP_Example
